version: 2

build:
  image: latest

python:
  version: "3.7"
  # Install our python package before building the docs
  install:
    - requirements: docs/requirements.txt
  system_packages: true

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip
  - pdf
